### ISSUE TITLE
console.Clear not clearing with transformers applied

### ISSUE THREAD

**Issue by laice** [BigJk/ramen#2]
I'm getting some confusing behaviour with the Clear method

`
err := con.Clear(0, con.Height-1, 1, 1)
`

This clears the target cell to the default black background

`
err := con.Clear(0, con.Height-1, 1, 1, t.Background(consolecolor.New(25, 0, 25)), t.Foreground(consolecolor.Green))
`

This does nothing and continues displaying previously printed text in the cell, and also does not return an error. Any thoughts?

**Comment by BigJk** [comment]
https://github.com/BigJk/ramen/pull/4
